### ISSUE TITLE
hashmem.com certificate expired

### ISSUE THREAD

**Issue by gavvvr** [fedotxxl/hashmem-idea#2]
Hi. Please upgrade https certificate. I do not even have an option in my Chrome to proceed on my own risk. 
PS: an Intellij plugin crashes at least with latest EAP, I sent an automatic bug report from Idea yesterday

**Comment by fedotxxl** [comment]
Hello. We updated ssl certificate. Sorry for this inconvenience

**Comment by gavvvr** [comment]
Hi. It works now. Thank you for the service :)
